### ISSUE TITLE
mismatch error

### ISSUE THREAD

**Issue by Nida228** [magic282/SEASS#11]
I am getting this error while running the code

RuntimeError: size mismatch, m1: [64 x 256], m2: [512 x 512] at c:\miniconda2\conda-bld\pytorch-cpu_1519449358620\work\torch\lib\th\generic/THTensorMath.c:1434

What is the fix of this line?

generator = nn.Sequential(
        nn.Linear(opt.dec_rnn_size // opt.maxout_pool_size, dicts['tgt'].size()),  # TODO: fix here
        nn.LogSoftmax())

**Comment by magic282** [comment]
Follow the example in the `run.sh` to use `-brnn`.
