### ISSUE TITLE
同学，你好，想询问一下你关于gigaword 数据集 上SEASS模型的参数设置。

### ISSUE THREAD

**Issue by sys1874** [magic282/SEASS#4]
同学，打扰了。
我最近在做关于gigaword数据集上复现你的论文《SEASS》。 发现训练的模型 在训练集 和验证集 上的偏差特别大。
所以想询问一下同学你模型的一些基本参数。（论文《SEASS》中有些地方写得并不是很详细。）

src 和 tgt的字典大小
encoder和decoder 的hidden state_size 、 num_layers
drop_out的概率
初始的learning rate
是否有使用 input_feed

beam_search 里面是否有使用其他trick 如 unk_replace等。

麻烦同学了。 万分感激！！！！！

**Comment by magic282** [comment]
Section 5.3: Implementation Details
